modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "GPLv3"

[[mods]]
modId = "hardcodepatcher"
version = "${version}"
displayName = "HardcodePatcher"
displayURL = ""
authors = "Me!"
description = '''

'''
logoFile = "icon.png"

[[dependencies.hardcodepatcher]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hardcodepatcher]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hardcodepatcher]]
modId = "architectury"
mandatory = true
versionRange = "[1.32.66,)"
ordering = "AFTER"
side = "BOTH"